### ISSUE TITLE
Undesired scrolling when switching tabs in index.html

### ISSUE THREAD

**Issue by franspaco** [ExpansionUrbanaMTY/Website#18]
### Repro steps:

1. Go to index.html
2. Navigate down to "Gráficas"
3. Click any of the 3 non-active tabs.

### Expected result:

- The tab switches.

### Observed result:

- The tab switches.
- The website scrolls up.

### Other observations:

- Each button seems to scroll the website up to a different fixed point.
- The page only scrolls up, never down.
- The issue only happens one per button per reload.

### Suggested solution:

The element `<ul uk-tab="" uk-switcher="connect: .switcher-container" class="uk-tab">`  has two event listeners for `click`. When the first one is removed the problem goes away. The tab event listener is being duplicated somewhere and the second listener is generating the bug.
![image](https://user-images.githubusercontent.com/2569404/88878688-4ee79980-d1dd-11ea-82c3-d3805d1e71de.png)

**Comment by franspaco** [comment]
Found a solution to remove the duplicate listener: Remove: `uk-switcher="connect: .switcher-container"` from the `<ul>` element.

**Comment by edvilme** [comment]
hmm ok ok, hare un commit mas en la noche que me pasen unos cambios. Se aprecia el feedback :D

**Comment by edvilme** [comment]
@franspaco just made PR. Think it works now, thx :D
